# Dockerfile - for CI tests using cypress
FROM ruby:3.1.2-slim-buster

# Ensure that we work in UTF 8
ENV LANG C.UTF-8 # ensure that the encoding is UTF8
ENV LANGUAGE C.UTF-8 # ensure that the encoding is UTF8
ENV CYPRESS_RAILS_PORT 5100

ENV RAILS_ENV=test
ENV NODE_ENV=development
ENV VITE_SUPPORTED_LOCALES=en,fr,pt_BR
ENV VITE_DEFAULT_LOCALE=fr
ENV VITE_FALLBACK_LOCALE=en

# Use a persistent volume for the gems installed by the bundler
ENV BUNDLE_PATH /var/bundler

ARG DEVISE_SECRET

# Common dependencies
RUN apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  build-essential gnupg2 curl less git vim

# Add NodeJS to sources list
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -yq libpq-dev postgresql-client nodejs 
# Cypress requirements
RUN apt-get -yq install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    truncate -s 0 /var/log/*log

RUN npm install --force --global yarn

# Install bundler for this Docker image
RUN gem install bundler:2.3.26

# WORKDIR /setup
ADD . /opt/labelr
WORKDIR /opt/labelr

#
RUN bin/bundle install --without development
RUN bin/vite install
RUN bin/rake assets:precompile

# We expose the port
EXPOSE 5100

# CMD script/labelr_start.sh
CMD ["tail", "-f", "/dev/null"]
